import {CategoryItem} from '../type';

const Animals: CategoryItem[] = [
  {
    id:1,
    name:'Cow',
    image:require('../assets/images/animals/cow.png'),
  },
  {
    id:2,
    name:'Tiger',
    image:require('../assets/images/animals/tiger.png'),
  },
  {
    id:3,
    name:'Capybara',
    image:require('../assets/images/animals/capybara.png'),
  },
  {
    id:4,
    name:'Giraffe',
    image:require('../assets/images/animals/giraffe.png'),
  },
  {
    id:5,
    name:'Kangaroo',
    image:require('../assets/images/animals/kangaroo.png'),
  },
  {
    id:6,
    name:'Orangutan',
    image:require('../assets/images/animals/orangutan.png'),
  },
  {
    id:7,
    name:'Snow Leopard',
    image:require('../assets/images/animals/snowLeopard.png'),
  },
  {
    id:8,
    name:'Jaguar',
    image:require('../assets/images/animals/jaguar.png'),
  },
  {
    id:9,
    name:'Armadillo',
    image:require('../assets/images/animals/armadillo.png'),
  },
  {
    id:10,
    name:'Hyena',
    image:require('../assets/images/animals/hyena.png'),
  },
  {
    id:11,
    name:'Squirrel',
    image:require('../assets/images/animals/squirrel.png'),
  },
  {
    id:12,
    name:'Koala',
    image:require('../assets/images/animals/koala.png'),
  },
  {
    id:13,
    name:'Mahmut',
    image:require('../assets/images/animals/mammut.png'),
  },
  {
    id:14,
    name:'Porcupine',
    image:require('../assets/images/animals/porcupine.png'),
  },
  {
    id:15,
    name:'Hedgehog',
    image:require('../assets/images/animals/hedgehog.png'),
  },
  {
    id:16,
    name:'Lemur',
    image:require('../assets/images/animals/lemur.png'),
  },
  {
    id:17,
    name:'Sheep',
    image:require('../assets/images/animals/sheep.png'),
  },
  {
    id:18,
    name:'Platypus',
    image:require('../assets/images/animals/platypus.png'),
  },
  {
    id:19,
    name:'Penguin',
    image:require('../assets/images/animals/penguin.png'),
  },
  {
    id:20,
    name:'Deer',
    image:require('../assets/images/animals/deer.png'),
  },
]
export {Animals};
