const Countries: CategoryItem[] = [
  {
    id:1,
    name:'Sri Lanka',
    image:require('../assets/images/animal.png'),
  },
  {
    id:2,
    name:'Bali',
    image:require('../assets/images/animal.png'),
  },
  {
    id:3,
    name:'Russia',
    image:require('../assets/images/animal.png'),
  },
  {
    id:4,
    name:'Washington DC',
    image:require('../assets/images/animal.png'),
  },
  {
    id:5,
    name:'Sicily',
    image:require('../assets/images/animal.png'),
  },
  {
    id:6,
    name:'Venice',
    image:require('../assets/images/animal.png'),
  },
  {
    id:7,
    name:'Kathmandu',
    image:require('../assets/images/animal.png'),
  },
  {
    id:8,
    name:'North Pole',
    image:require('../assets/images/animal.png'),
  },
  {
    id:9,
    name:'Monaco',
    image:require('../assets/images/animal.png'),
  },
  {
    id:10,
    name:'Paris',
    image:require('../assets/images/animal.png'),
  },
  {
    id:11,
    name:'Lal Kila',
    image:require('../assets/images/animal.png'),
  },
  {
    id:12,
    name:'Maldives',
    image:require('../assets/images/animal.png'),
  },
  {
    id:13,
    name:'Hungary',
    image:require('../assets/images/animal.png'),
  },
  {
    id:14,
    name:'Bulgaria',
    image:require('../assets/images/animal.png'),
  },
  {
    id:15,
    name:'Rome',
    image:require('../assets/images/animal.png'),
  },
  {
    id:16,
    name:'Greece',
    image:require('../assets/images/animal.png'),
  },
  {
    id:17,
    name:'Kyrgyzstan',
    image:require('../assets/images/animal.png'),
  },
  {
    id:18,
    name:'Djibouti',
    image:require('../assets/images/animal.png'),
  },
  {
    id:19,
    name:'Lithuania',
    image:require('../assets/images/animal.png'),
  },
  {
    id:20,
    name:'Brunei',
    image:require('../assets/images/animal.png'),
  },
]
export {Countries};
