const Vegetables: CategoryItem[] = [
  {
    id:1,
    name:'Tomato',
    image:require('../assets/images/animal.png'),
  },
  {
    id:2,
    name:'Pumpkin',
    image:require('../assets/images/animal.png'),
  },
  {
    id:3,
    name:'Bread',
    image:require('../assets/images/animal.png'),
  },
  {
    id:4,
    name:'Kimbap',
    image:require('../assets/images/animal.png'),
  },
  {
    id:5,
    name:'Sushi',
    image:require('../assets/images/animal.png'),
  },
  {
    id:6,
    name:'Tempura',
    image:require('../assets/images/animal.png'),
  },
  {
    id:7,
    name:'Biryani',
    image:require('../assets/images/animal.png'),
  },
  {
    id:8,
    name:'Udon',
    image:require('../assets/images/animal.png'),
  },
  {
    id:9,
    name:'Durian',
    image:require('../assets/images/animal.png'),
  },
  {
    id:10,
    name:'Spam',
    image:require('../assets/images/animal.png'),
  },
  {
    id:11,
    name:'Kimchi',
    image:require('../assets/images/animal.png'),
  },
  {
    id:12,
    name:'Tofu',
    image:require('../assets/images/animal.png'),
  },
  {
    id:13,
    name:'Dhido',
    image:require('../assets/images/animal.png'),
  },
  {
    id:14,
    name:'Tteokbokki',
    image:require('../assets/images/animal.png'),
  },
  {
    id:15,
    name:'Matcha',
    image:require('../assets/images/animal.png'),
  },
  {
    id:16,
    name:'Mochi',
    image:require('../assets/images/animal.png'),
  },
  {
    id:17,
    name:'Cutlet',
    image:require('../assets/images/animal.png'),
  },
  {
    id:18,
    name:'Dorameon Cake',
    image:require('../assets/images/animal.png'),
  },
  {
    id:19,
    name:'Chia Seeds',
    image:require('../assets/images/animal.png'),
  },
  {
    id:20,
    name:'Oats',
    image:require('../assets/images/animal.png'),
  },
]
export {Vegetables};
